MLP : false
LSTM : true
TRANSFORMER : false

POLICY_LAYERS : [277, 256, 256, 256, 34]
# POLICY_LAYERS : [246, 256, 256, 256, 34]
VALUE_LAYERS : [277, 256, 256, 256, 1]
# VALUE_LAYERS : [246, 256, 256, 256, 1]
HIDDEN_SIZE : 256
NUM_LAYERS : 1
