MLP : true
LSTM : false
TRANSFORMER : false

# POLICY_LAYERS : [27, 128, 128, 128, 16] # fix this with ant obs + action dim
# POLICY_LAYERS : [81, 300, 300, 16] # fix this with ant obs + action dim
POLICY_LAYERS : [118, 256, 256, 16] # fix this with ant obs + action dim
# POLICY_LAYERS : [29, 64, 64, 16] # fix this with ant obs + action dim
# VALUE_LAYERS : [27, 128, 128, 128, 1]
# VALUE_LAYERS : [81, 300, 300, 1]
# VALUE_LAYERS : [29, 64, 64, 1]
VALUE_LAYERS : [118, 256, 256, 1]
HIDDEN_SIZE : 64
NUM_LAYERS : 1
