terminate_when_unhealthy: true
include_standing_up_flag: true
chase_reward: true
exclude_current_positions_from_observation: true
forward_reward_weight: 0.0
ctrl_cost_weight: 0.1
healthy_reward: 1.0
healthy_z_range:
  - 0.8
  - 2.5
reset_noise_scale: 0.01
chase_reward_weight: 5.0
standup_cost : 1.5
and_done_flag : false
or_done_flag : true
include_other_agents_state: false
include_full_state_other_agents : true
chase_reward_inverse : true
tag_reward : true
tag_reward_weight : 10.0
