terminate_when_unhealthy: true
exclude_current_positions_from_observation: true # Change this to true
use_contact_forces: false
contact_cost_weight: 0.0005
ctrl_cost_weight: 0.5
# ctrl_cost_weight: 0.1
healthy_reward: 1.0
healthy_z_range:
  - 0.2
  - 1.0
contact_force_range:
  - -1.0
  - 1.0
reset_noise_scale: 0.1
