terminate_when_unhealthy: true
exclude_current_positions_from_observation: false
forward_reward_weight: 1.0
ctrl_cost_weight: 0.1
healthy_reward: 1.0
healthy_z_range:
  - 0.8
  - 2.5
reset_noise_scale: 0.02
