terminate_when_unhealthy: true
include_standing_up_cost: false
chase_reward: false
exclude_current_positions_from_observation: true
forward_reward_weight: 1.5
ctrl_cost_weight: 0.1
healthy_reward: 5.0
healthy_z_range:
  - 1.0
  - 2.5
reset_noise_scale: 0.01
chase_reward_weight: 1.0
