terminate_when_unhealthy: false
exclude_current_positions_from_observation: false # Change this to true
use_contact_forces: false
contact_cost_weight: 0.0000
ctrl_cost_weight: 0.00
# ctrl_cost_weight: 0.1
healthy_reward: 0.0
chase_reward_weight : 1.0
forward_reward_weight: 0.0
healthy_z_range:
  - 0.2
  - 1.0
contact_force_range:
  - -1.0
  - 1.0
reset_noise_scale: 0.2
chase_reward_inverse : false
full_state_other_agents : true
tag_reward_weight : 0.0
backend : "positional"
random_spawn : true
