num_timesteps: 5_000_000_000
eval_reward_limit: 10_000
eval_frequency: 1000
episode_length: 100
unroll_length: 5
num_minibatches: 32
num_update_epochs: 4
discounting: 0.98
learning_rate: 0.0003
entropy_cost: 0.02
num_envs: 2048
batch_size: 1024
env_name: ants
device: cuda
debug: false
device_idx: 0
eval_flag : true
notebook: false
model_path : null
runnning_avg_length : 5
time_series : false
