num_timesteps: 100000000
eval_reward_limit: 9000
eval_frequency: 500
episode_length: 1000
unroll_length: 10
num_minibatches: 32
num_update_epochs: 8
discounting: 0.97
learning_rate: 0.0005
entropy_cost: 0.002
num_envs: 2048
batch_size: 512
env_name: humanoids
device: cuda
debug: false
device_idx: 0
eval_flag : true
notebook: false
# model_path : null
model_path: ./models/20240226_092325_ppo_humanoids_standing.pt
