num_timesteps: 1000000000
eval_reward_limit: 10000
eval_frequency: 50
episode_length: 1000
unroll_length: 10
num_minibatches: 32
num_update_epochs: 8
discounting: 0.97
learning_rate: 2e-4
entropy_cost: 2e-3
num_envs: 2048
batch_size: 512
env_name: humanoids
device: cuda
debug: True
device_idx: 0
notebook: false
model_path: null
