num_timesteps: 500_000_000
eval_reward_limit: 10_000
eval_frequency: 100
episode_length: 1000
unroll_length: 5
num_minibatches: 32
num_update_epochs: 4
discounting: 0.97
learning_rate: 0.0001
entropy_cost: 0.02
num_envs: 2048
batch_size: 1024
env_name: ants
device: cuda
debug: false
device_idx: 0
eval_flag : true
notebook: false
model_path : null
# model_path : "models/20240329_150029_ppo_ants.pt"
runnning_avg_length : 3
full_state : false
time_series : false
