num_timesteps: 500_000_000
eval_reward_limit: 30000
eval_frequency: 1000
episode_length: 1000
unroll_length: 3
num_minibatches: 32
num_update_epochs: 8
discounting: 0.97
learning_rate: 0.001
entropy_cost: 0.0001
num_envs: 1024
batch_size: 256
env_name: humanoids
device: cuda
debug: false
device_idx: 0
eval_flag : true
notebook: false
model_path : null
runnning_avg_length : 3
time_series : false
