num_timesteps: 500000000
eval_reward_limit: 30000
eval_frequency: 1000
episode_length: 1000
unroll_length: 5
num_minibatches: 32
num_update_epochs: 8
discounting: 0.99
learning_rate: 0.00005
entropy_cost: 0.002
num_envs: 2048
batch_size: 512
env_name: humanoids
device: cuda
debug: false
device_idx: 0
eval_flag : true
notebook: false
# model_path : null
model_path : ./models/20240305_173445_ppo_humanoid_copy_2.pt
# model_path : ./models/20240227_115117_ppo_humanoid_standing_dim_246_copy_2.pt
runnning_avg_length : 3
full_state : false
