num_timesteps: 5_000_000_000
eval_reward_limit: 10_000
eval_frequency: 1000
episode_length: 1000
unroll_length: 5
num_minibatches: 32
num_update_epochs: 8
discounting: 0.97
learning_rate: 0.0003
entropy_cost: 0.0005
num_envs: 2048
batch_size: 512
env_name: humanoids
device: cuda
debug: false
device_idx: 0
eval_flag : true
notebook: false
# model_path : Null
model_path : "models/20240424_145208_ppo_humanoids_94945280.pt"
runnning_avg_length : 3
time_series : false
