num_timesteps: 50_000_000
eval_frequency: 100
episode_length: 1000
unroll_length: 10
num_minibatches: 32
num_update_epochs: 8
discounting: 0.98
learning_rate: 0.001
entropy_cost: 0.001
num_envs: 1024
batch_size: 512
env_name: humanoid
device: cuda
