num_timesteps: 5000000000
eval_reward_limit: 20000
eval_frequency: 1000
episode_length: 1000
unroll_length: 5
num_minibatches: 32
num_update_epochs: 8
discounting: 0.99
learning_rate: 0.0001
entropy_cost: 0.003
num_envs: 2048
batch_size: 512
env_name: humanoids
device: cuda
debug: false
device_idx: 0
eval_flag : true
notebook: false
# model_path : null
model_path : ./models/20240306_095032_ppo_humanoids_good.pt
# model_path : ./models/20240307_111644_ppo_humanoids.pt
runnning_avg_length : 3
full_state : false
