num_timesteps: 3_000_000_000
eval_reward_limit: 10_000
eval_frequency: 100
episode_length: 1000
unroll_length: 5
num_minibatches: 32
num_update_epochs: 8
discounting: 0.97
learning_rate: 0.0003
# learning_rate: 0.001
entropy_cost: 0.0001
# entropy_cost: 0.001
# entropy_cost: 0.01
num_envs: 4048
batch_size: 1024
env_name: ants
device: cuda
debug: false
device_idx: 0
eval_flag : true
notebook: false
model_path : null
runnning_avg_length : 5
time_series : false
